#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: school-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: school_management
#      MYSQL_USER: school_user
#      MYSQL_PASSWORD: school_pass
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - school-network
#
#  redis:
#    image: redis:7-alpine
#    container_name: school-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - school-network
#
#  spring-boot-app:
#    build: .
#    container_name: school-backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_management?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: school_user
#      SPRING_DATASOURCE_PASSWORD: school_pass
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - mysql
#      - redis
#    networks:
#      - school-network
#
#volumes:
#  mysql_data:
#
#networks:
#  school-network:
#    driver: bridge